/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as ReputationRouteImport } from './routes/reputation'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReputationRoute = ReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/connections': typeof ConnectionsRoute
  '/publishing': typeof PublishingRoute
  '/reputation': typeof ReputationRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/connections': typeof ConnectionsRoute
  '/publishing': typeof PublishingRoute
  '/reputation': typeof ReputationRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/connections': typeof ConnectionsRoute
  '/publishing': typeof PublishingRoute
  '/reputation': typeof ReputationRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connections'
    | '/publishing'
    | '/reputation'
    | '/studio'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connections'
    | '/publishing'
    | '/reputation'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/connections'
    | '/publishing'
    | '/reputation'
    | '/studio'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandRoute: typeof BrandRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  ConnectionsRoute: typeof ConnectionsRoute
  PublishingRoute: typeof PublishingRoute
  ReputationRoute: typeof ReputationRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reputation': {
      id: '/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof ReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandRoute: BrandRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  ConnectionsRoute: ConnectionsRoute,
  PublishingRoute: PublishingRoute,
  ReputationRoute: ReputationRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
